# Generated by Django 5.2 on 2025-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_created_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('HW', 'Homework'), ('PR', 'Project'), ('EX', 'Exam')], default='HW', max_length=8),
        ),
        migrations.AddField(
            model_name='task',
            name='task_urgency',
            field=models.CharField(choices=[('CR', 'Critical'), ('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], default='LO', max_length=8),
        ),
    ]
